### PR TITLE
Added LED_BUILTIN to Board_Defs.h

### PR DESCRIPTION
**Pull request by squintz**
The Arduino project has added LED_BUILTIN to their official list of Constants. See https://www.arduino.cc/en/Reference/Constants

They have also updated their examples to use LED_BUILTIN which means it must be defined in variants of Board_Defs.h in order to compile some of their examples. This will likely be an issue in most chipKIT variants.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
Unfortunately this needs to be done on a per-board basis, as many boards do not have pin 13 connected to an LED. (Thus the reason Arduino went to a constant rather than using "13", because many of their boards don't have it on 13 anymore either.) Each board's variant file will need to get this define.

**Comment by majenkotech** [comment]
Why not

    #define PIN_LEDBUILTIN PIN_LED1

...?

**Comment by EmbeddedMan** [comment]
Ahhh! Yes, that would work well I think.

*Brian

**Comment by JacobChrist** [comment]
This is the same at #235 and #276.  Also, #235 talks about changes to SPI.

Jacob

**Comment by EmbeddedMan** [comment]
squintz, I think Matt's idea of adding just one 
#define LED_BUILTIN PIN_LED1
in one common place (which will work because every board's variant file will already have PIN_LED1 defined appropriately) may be a better way to go than adding this to every variant file.

**Comment by JacobChrist** [comment]
squintz, I think Matt's idea of adding just one 
#define LED_BUILTIN PIN_LED1
in one common place (which will work because every board's variant file will already have PIN_LED1 defined appropriately) may be a better way to go than adding this to every variant file.

**Comment by majenkotech** [comment]
I don't think he can hear you above the noise of the commits.

**Comment by squintz** [comment]
Oops, sorry! I was in the middle of changing it while you guys were replying. I can change it to PIN_LED1

**Comment by squintz** [comment]
So before I go making the changes again... where would the one common place be that #define LED_BUILTIN PIN_LED1 should go? It only took a couple minutes to add it to each board file so it should only take a few minutes to undo what I did.

**Comment by JacobChrist** [comment]
pins_arduino.h?

**Comment by squintz** [comment]
Makes sense to me. I'll close this pull request and pretend it never happened.

**Pull request closed without merging**
