### PR TITLE
Added LFN support to DFATFS plus other big improvements

### PR DESCRIPTION
**Pull request by majenkotech**
Added WCHAR conversion functions and enabled LFN support (dynamic stack based).

This now allows you to use more than just old fashioned 8.3 filenames.

### CODE REVIEW

**Comment by JacobChrist** [comment]
Nice!

On Fri, May 13, 2016 at 2:37 PM, Majenko Technologies <
notifications@github.com> wrote:

> Added WCHAR conversion functions and enabled LFN support (dynamic stack
> based).
>
> This now allows you to use more than just old fashioned 8.3 filenames.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/chipKIT32/chipKIT-core/pull/216
> Commit Summary
>
>    - Added LFN support to DFATFS
>
> File Changes
>
>    - *M* pic32/libraries/DFATFS/utility/fs_ff.c
>    <https://github.com/chipKIT32/chipKIT-core/pull/216/files#diff-0> (24)
>    - *M* pic32/libraries/DFATFS/utility/fs_ffconf.h
>    <https://github.com/chipKIT32/chipKIT-core/pull/216/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/chipKIT32/chipKIT-core/pull/216.patch
>    - https://github.com/chipKIT32/chipKIT-core/pull/216.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT-core/pull/216>
>



-- 
Jacob Christ
*ProLinear/PONTECH, Inc.*
1-877-985-9286 Phone
1-413-235-1651 Fax
http://www.pontech.com

**Comment by majenkotech** [comment]
chipkitbot failed to download the compiler... muppet...

Can you trigger a retest?

**Comment by EmbeddedMan** [comment]
Adam/Matthew - I forgot how to trigger chipkit bot to rerun the compile. Can one of you remind me?

**Comment by majenkotech** [comment]
retest this please

**Comment by majenkotech** [comment]
retest this please

**Comment by majenkotech** [comment]
Third time lucky...  Looks like W&L's network is a little shaky.

**Comment by majenkotech** [comment]
I just added a new filesystem driver (separate library, ROMVOL) which is a copy of the RAMVOL library but with some bits cut out and changed around slightly.

This allows you to include a read-only filesystem in your sketch through whatever means you have at your disposal (convert to C code in an array for MPIDE or Arduino, include the binary object in UECIDE) and access the files within it as if it were an SD card.

On Linux I create images with:

    $ dd if=/dev/zero of=fs.img bs=512 count=<num of sectors>
    $ newfs.vfat fs.img
    $ sudo mount -o loop fs.img /mnt
    $ ... copy files to /mnt ...
    $ sudo umount /mnt

**Comment by majenkotech** [comment]
We now have an almost Arduino-standard interface to the DFILE class now that it inherits from Stream. There is absolutely no excuse for not inheriting from Stream.

**Comment by majenkotech** [comment]
retest this please

**Comment by majenkotech** [comment]
One more disk driver for FATFS. This one is a RAM disk that stores its data on a number of 23LC1024 (or similar) SPI SRAM chips.

**Comment by EmbeddedMan** [comment]
I have tested the basic SDWriteRead example (which, I think is the ONLY example we have for FATFS) with a long filename on Fubarino SD and it worked perfectly. I did not test the other file system types. It would be really cool if somebody could add some simple demos for the RAMVOL and ROMVOL.

**Pull request merged**
