### PR TITLE
FATFS

### PR DESCRIPTION
**Pull request by KeithV**
1.       Modified the SD library to use alternate CS functions as provided in the Board_Defs.h file under the _ALT_SD_SPI_CHIP_SELECT_ compiler switch
2.       Moved the Uno32/uC32/MAX32 CS functions in to their respective Boards_data.c (got the MRF/INT special sauce out of SD library Sd2Card.cpp).
3.       Moved all of the Digilent board specifications out of Sd2PinMap.h and into the Board_Defs.h under the _uSD_SPI_CONFIG_ compiler switch
4.       Moved all of the Digilent WiFi SPI configuration out of NetworkProfile.x and put it in the Board_Defs.h under the _MRF24_SPI_CONFIG_ compiler switch
5.       Moved all of the Digilent internal Mac/Phy network configuration out of NetworkProfile.x and put into the Board_Defs.h under the _IM8720PHY_PIN_CONFIG_ compiler switch
6.       Updated the SoftSPI library to use the core timer instead of “for loops” for software timing; and allowed for more than just 80MHz F_CPU (supports any F_CPU).
7.       Added a base class DGSPI to SoftSPI and DSPI to be used as a common interface in the DSDVOL to support common coding for both Hardware or bit banged SPI.
8.       Added the FatFs code in a new DFATFS library
9.       Added the DSDVOL library to support SPI / SD, both hardware and Bit Banged SPI
10.   Added the SDRead example in the DSDVOL.
11.   Updated the HTTPServer example to the deWebIOServer example (Firmata like example).
12.   Updated the deWebIOServer to work with the DSDVOL/DFATFS for SD access
13.   Updated the deWebIOServer to work with the following boards:
a.       chipKIT WiFIRE
b.      chipKIT WF32
c.       chipKIT uC32 + WiFiShield
d.      chipKIT MAX32 + WiFiShield
e.      chipKIT Pro MX4 + PmodSD + PmodWiFI
f.        chipKIT Pro MX7 + PmodSD + (PmodWiFi –OR-- internal Mac & Phy)
14.   Added DSDVOL/FatFs support in the variants (Board_Defs.h) for the following boards:
a.       chipKIT WiFIRE
b.      chipKIT WF32
c.       chipKIT Uno32 + WiFiShield
d.      chipKIT uC32 + WiFiShield
e.      chipKIT MAX32+WiFiShield
f.        chipKIT Pro MX4 + PmodSD 
g.       chipKIT Pro MX7 + PmodSD 
h.      chipKIT MX3 + PmodSD
i.         chipKIT Cmod + PmodSD
j.        chipKIT DP32 + PmodSD
15.   Fixed a typo in boards.txt for the Cerebot 32MX7 board name

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
YES, chipkiptbot, I'm WORKING on it. :-)

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by adamwolf** [comment]
@EmbeddedMan, I'm going to give it 10 minutes or so, and then I'll tell it OK to test.  

I have your github username in every single box where I have mine, but it listens to me, and not to you.

**Comment by EmbeddedMan** [comment]
That's OK. My kids don't listen to me either, and I still love them. Mostly.

*Brian

**Comment by adamwolf** [comment]
Except there's no one to bug for a patch for your kids...

wait, did I miss that in dad class?

**Comment by adamwolf** [comment]
ok to test

**Comment by adamwolf** [comment]
Hi folks, the build says it failed here:

/var/lib/jenkins/jobs/chipKIT-core PR Builder/workspace/build.xml:256:
The following error occurred while executing this line:
/var/lib/jenkins/jobs/chipKIT-core PR Builder/workspace/build.xml:136:
src '/var/lib/jenkins/jobs/chipKIT-core PR
Builder/workspace/tmp/pic32-tools-chipKIT-cxx-master-Linux32-image.zip'
doesn't exist.



I will wipe out the job and attempt a rebuild in case it's an issue on the
chipkitbot side.

**Comment by adamwolf** [comment]
retest this please
chipkitbot

**Comment by KeithV** [comment]
Adam,

 

Clarify what I need to do, if anything?

 

KeithV

**Comment by EmbeddedMan** [comment]
Keith, would you like me to close this PR?

**Comment by KeithV** [comment]
Yes, I am redoing it with the warning fixes, plus adding the fixes I made.

**Comment by KeithV** [comment]
Brian,

 

I think you still have an issue in platform.txt, but I am not going to fix it because I don’t want to get into a merge conflict. You have put both the temp dir and tempdir/sketch on some of the –I paths. I don’t think we need to put  the temp dir on the include path anymore do we? What you have doesn’t seem to hurt anything, just unnecessary (I think).

 

KeithV

**Pull request closed without merging**
