### PR TITLE
Update for testing.

### PR DESCRIPTION
**Pull request by adamwolf**
This is a chipkitbot test. :(

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
It appears this build did not in fact succeed.

*Brian

**Comment by adamwolf** [comment]
Yeah, the job is failing on some redirects from github on downloading the
Windows toolchain?  It works when I click it in a browser, but not from
ant.  I need to troubleshoot it.

**Comment by EmbeddedMan** [comment]
Any luck on this Adam?

**Comment by adamwolf** [comment]
eh. It's building successfully, but somewhere between it and Github the
notification is being lost. :(

**Comment by adamwolf** [comment]
It's working now.  I'm setting up a different plugin, so when this one
inevitably breaks again, we'll have something ready.

**Comment by EmbeddedMan** [comment]
I don't believe we need this around anymore, so I'm closing it. Please re-open (Adam) if it pleases you.

**Pull request closed without merging**
