### PR TITLE
Usb stack and board cleanup

### PR DESCRIPTION
**Pull request by majenkotech**
Integration of the new USB stack. Also a cleanup of the boards.txt, discarding unwanted and obsolete board entries, and merging multiple entries together using the new Arduino Menu system.

### CODE REVIEW

**Comment by majenkotech** [comment]
This PR is mainly for chipkitbot to test and build packages from for us to try out and experiment with.  I am also wondering what he thinks of the new boards structure.

**Comment by adamwolf** [comment]
hey chipkitbot
retest this please

**Comment by squintz** [comment]
Are we still waiting on more testing to release this?

**Comment by majenkotech** [comment]
Yes. It will come out in chipKIT-Core 2.0 sometime before Christmas if all goes well.

**Comment by EmbeddedMan** [comment]
Yes please! What's there is very, very good, and very stable, but has only
been used by just a couple folks, and if we're going to switch over we need
a lot more testing. Thank you!!

*Brian

**Comment by EmbeddedMan** [comment]
OK, time to merge this sucker. I've been using it almost exclusively for a couple months now with no problems, although I'm not pushing the new stack very hard (just using it as a replacement to the old USB serial).

**Pull request merged**
