### PR TITLE
Fixed checksums

### PR DESCRIPTION
**Pull request by majenkotech**
Fixed the checksums for Windows pic32prog (new version) and arm pic32prog (ancient version).

### CODE REVIEW

**Comment by majenkotech** [comment]
chipkitbot retest this please

**Comment by majenkotech** [comment]
This will never succeed - all the pic32-tools URLs are b0rken.

**Comment by EmbeddedMan** [comment]
Nope. With this change, the Windows download is now broken. Before this change the Windows download was working. I'll dig into it now and see what broke.

**Comment by majenkotech** [comment]
All the checksums test out fine now though.

**Comment by EmbeddedMan** [comment]
Well, the Windows pic32prog crc does not make the Arduino IDE happy, at
least for me.

**Comment by majenkotech** [comment]
Booting my VM now...

**Comment by majenkotech** [comment]
Delete the files from your staging directory?

**Pull request merged**
