### PR TITLE
Added pin def file for 124 pins

### PR DESCRIPTION
**Pull request by majenkotech**
This is actually the same as for 144 pins by the looks of things. Added as a separate file anyway for both simplicity and future flexibility.

### CODE REVIEW

**Comment by JacobChrist** [comment]
I just tried this same change on my side and it still would not compile.  I was getting this message:

C:\Users\Jacob Christ\AppData\Local\Arduino15\packages\chipKIT\hardware\pic32\1.3.1\cores\pic32/p32_defs.h:739:41: fatal error: pps/pins_mz_124.h: No such file or directory

             #include "pps/pins_mz_124.h"

May be windows caching the directory before I created the pps/pins_mz_124.h file.

Jacob

**Comment by majenkotech** [comment]
Maybe you typo'd the filename, or placed it in the wrong place?

**Comment by JacobChrist** [comment]
Just found it.  I called the file "pins_mz_124 .h" (space between 4 and .)

Jacob

**Comment by majenkotech** [comment]
D'oh ;)

**Pull request merged**
