### PR TITLE
Pontech variants

### PR DESCRIPTION
**Pull request by JacobChrist**
This pull request address issue #292.  It also does some minor refactor of other PONTECH variants so that the folder naming convention is consistent from board to board.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
Jacob, this all looks good to me, although I don't understand enough about our analog code and the PIC32's analog peripheral to know everything is correct.

How much testing with analog reads did you do on non-MZ boards?

**Comment by JacobChrist** [comment]
The MZ code is from Keith I just split it up. Seems to be working for at
least 5 ADC channels we are using. Sine there is really no MZ board and the
WiFire code is untouched I am pretty sure nothing is broken.

Jacob

**Comment by JacobChrist** [comment]
As a matter of fact the the function names still say WiFire. A fact I
realized recently and should have renamed them to be more generic. This is
for another issue though....

On Nov 27, 2016 4:31 PM, "Jacob Christ" <jacob@pontech.com> wrote:

The MZ code is from Keith I just split it up. Seems to be working for at
least 5 ADC channels we are using. Sine there is really no MZ board and the
WiFire code is untouched I am pretty sure nothing is broken.

Jacob

**Comment by EmbeddedMan** [comment]
Jacob,

Understood - that the intent was only to change behavior for MZ parts. But
from my (brief) code review, it looks like non-MZ parts will also have
_some_ limited changes in the overall flow through ReadAnalog. Have you
tested on at least one non-MZ board to make sure all existing analog
functionality remains working?

*Brian

**Comment by JacobChrist** [comment]
I have not. I have tested one channel on at least 3 mx boards. I can do
this check tomorrow.

Jacob

**Comment by EmbeddedMan** [comment]
Thanks Jacob. If you find any problems, file a new issue so we can track
any changes that are needed.

*Brian

**Pull request merged**
