### PR TITLE
Wire.write() to support passing uint32_t (and by promotion uint_16_t).

### PR DESCRIPTION
**Pull request by JacobChrist**
Compiles, not tested on hardware.  I think its going to work.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by adamwolf** [comment]
retest this please

**Comment by adamwolf** [comment]
retest this please

(this is a directive to chipkitbot, not a code quality judgement 😄 )

**Comment by adamwolf** [comment]
retest this please

one last time before bed, i'll look tomorrow

**Comment by EmbeddedMan** [comment]
10 print "retest this please"
20 goto 10

run

Will that help?

**Comment by JacobChrist** [comment]
What do you me retest? I never tested in the first place.  I will test
tomorrow when I am back at school. On a side note my coworkers often liken
me to a robot.

Jacob

**Comment by EmbeddedMan** [comment]
These messages are for chipKIT bot, not us humans. It will also be great
for you to test the change (although I agree with you that it should not
cause any problems), but Adam is trying to kick chipKIT bot into rebuilding
this pull request.

*Brian

**Comment by JacobChrist** [comment]
I know. I guess being a smartass doesn't come across in written form too
well.

Jacob

**Comment by adamwolf** [comment]
ok to retest

**Comment by adamwolf** [comment]
retest this please

**Comment by JacobChrist** [comment]
I have confirmed that this changes work in with the Ada fruit example program and library.  I think its ready to merge.

**Pull request merged**
