### PR TITLE
fix WiFi examples,MX7 DSPI, and OpenScope variants

### PR DESCRIPTION
**Pull request by KeithV**
this updates the MX7 to issue 171 and resolves issue 169 and updates the OpenScope variants. Also fixes some flash sizes for the WiFIRE and OpenScope

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
Keith this looks great, but the commit has conflicts that will need to be resolved before it can be merged.

**Comment by KeithV** [comment]
I don't understand? chipKIT bot built it, I downloaded it; it works. Where are the conflicts? How do I fix that?

**Comment by EmbeddedMan** [comment]
Keith,

When you submitted your PR, there were no conflicts. Some commit (one of
the PRs that's been merged since then) must have had a change on the same
line as one of your changes, thus the new conflict.

To fix the conflict, you can use the command line git tools to figure out
exactly where the conflict is, and resolve it. But I have no idea how to do
that (I'm not smart enough to use the command line git client).

So what I've done in the past is checked out a fresh copy of chipKIT-core
(which will have all of the latest merges in it, but not your PR), and then
do a diff between that and the copy of chipKIT-core you used to develop the
PR. There will be some differences, and at least one conflict. Go back and
edit the conflict in your copy of chipKIT-core that you used to develop the
PR, and then commit the change. If everything works as it's supposed to,
GitHub will pick up the change to your repo (that fixes the conflict), and
declare that your PR is now OK to be merged.

If that doesn't work, we'll figure out what to do next. (I've run into this
several times with my own PRs and some other people's PRs)

*Brian

**Comment by KeithV** [comment]
Brian,

 

I am resolving the conflict, but I am getting a warning on the Lenny board… that needs to be fixed.

 

KeithV

**Comment by EmbeddedMan** [comment]
Fair enough - throw it in an issue and I'll assign it to him.

*Brian

**Comment by EmbeddedMan** [comment]
Looks awesome. Merging.

**Pull request merged**
