### PR TITLE
Split PPS into separate per-chipgroup files and added MX370

### PR DESCRIPTION
**Pull request by majenkotech**
* The mess that was p32_defs.h has now been split into a number of
  smaller logical units to be combined in different combinatins
  for different chips. This makes it so much easier to work out what
  is going on where.

* The MX370 chips have been added as CPU defs and PPS entries have been
  created for them.

**Note: This change could break PPS if I missed something out by accident. Thorough testing of various PPS peripherals on the relevant boards is recommended before merge.**

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
Matt - I am still planning on reviewing this code carefully and testing it out on some PPS boards like the FB Mini soon.

**Comment by majenkotech** [comment]
Are you still planning on reviewing this sometime soon? I have another PR I want to get in (only a small one) and I want to clean my repo first...

**Comment by EmbeddedMan** [comment]
Matt,

Yes, I am. I've just been snowed under. I won't have time before Sunday,
but I'll try to get to it on Sunday for sure. So sorry it's taking this
long-

*Brian

**Comment by majenkotech** [comment]
It's ok, I did another fork elsewhere for the other pull request.

**Comment by EmbeddedMan** [comment]
I've spot checked a DP32, a Fubarino Mini, and a WiFire. I've tested a PPS peripheral on each one (hardware USART) and they work exactly as they did before this PR. That is certainly not an exhaustive test, but it at least shows that, at least for those processors,  you got the PPS mapping correct. I'm going to leave further testing for the wider audience of the new build, and merge this bad boy now.

**Pull request merged**
