### PR TITLE
fix warnings in SD

### PR DESCRIPTION
**Pull request by KeithV**
Fix SD warnings, also correct change notice in Uno32 and Max32

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by KeithV** [comment]
Thanks,

 

Downloading now and trying!

 

Happy New Year.

KeithV

**Comment by KeithV** [comment]
Adam….. FYI

**Comment by KeithV** [comment]
AND….

 

 



 

From: Keith Vogel [mailto:KeithV@KRVogel.com] 
Sent: Wednesday, December 30, 2015 4:15 PM
To: 'chipKIT32/chipKIT-core'; 'chipKIT32/chipKIT-core'
Cc: Adam Wolf (adamwwolf@gmail.com) (adamwwolf@gmail.com)
Subject: RE: [chipKIT-core] fix warnings in SD (#133)

 

Adam….. FYI

**Comment by KeithV** [comment]
However,

 

It seems to work with the release version of Arduino 1.6.7!

 

KeithV

 

From: Keith Vogel [mailto:KeithV@KRVogel.com] 
Sent: Wednesday, December 30, 2015 4:20 PM
To: 'chipKIT32/chipKIT-core'; 'chipKIT32/chipKIT-core'
Cc: Adam Wolf (adamwwolf@gmail.com) (adamwwolf@gmail.com)
Subject: RE: [chipKIT-core] fix warnings in SD (#133)

 

AND….

 

 



 

From: Keith Vogel [mailto:KeithV@KRVogel.com] 
Sent: Wednesday, December 30, 2015 4:15 PM
To: 'chipKIT32/chipKIT-core'; 'chipKIT32/chipKIT-core'
Cc: Adam Wolf (adamwwolf@gmail.com) (adamwwolf@gmail.com)
Subject: RE: [chipKIT-core] fix warnings in SD (#133)

 

Adam….. FYI

**Comment by EmbeddedMan** [comment]
Yes, the problem of the *.py files in the pic32-tools zip downloads is an
open issue : https://github.com/chipKIT32/chipKIT-cxx/issues/6

I hope this can be resolved pretty soon.

In the meantime, I have created my own versions of the pic32-tools .zip
files and placed them in the v1.0.1 chipKIT-core release. (That don't have
the *.py files in them.)

*Brian

**Comment by KeithV** [comment]
Well it didn’t seem to hurt anything other than I could not extract it.

 

Things seem to be working.

 

KeithV

**Comment by EmbeddedMan** [comment]
Keith - that's good to hear. In the next couple days, we're going to be
implementing a change to the folder layout when you do a 'manual-copy' of
chipKIT-core. I'll be explaining it in more detail shortly, but it is
required so that we can use the same platform.txt file for both manual and
automatic installs of chipKIT-core. The bottom line is that you'll need to
update chipKIT-core, pic32-tools (the compiler) and pic32prog separately
rather than as one huge download, which has its pros and cons.

*Brian

**Comment by KeithV** [comment]
Thanks Brian,

 

I think I understand as the auto download has links to components, not just one package.

 

But, with the chipKITBOT, I would think making many different packages would be easy and automatic. We could make the manual install package as well as the auto download packages, no?

 

KeithV

**Comment by EmbeddedMan** [comment]
Keith,

Unfortunately this would involve either having two separate platform.txt
files (which would be a pain to maintain separately) or would involve some
'build time text substitution magic' which, while absolutely possible,
isn't an added complexity that will help us in the long run. Keeping the
build process as simple as possible will  help us I think.

Also, I don't want chipkitbot to be the _only_ place we can build our
outputs. Being able to do it on all of our own machines is super easy right
now, and I'd like to keep it that way if we can.

Now, there is a good opportunity to come up with a simple installer as part
of the build process, which could make the 'manual install process' as
simple as double clicking on a .exe file and having it put everything
(chipkit-core, pic32-tools and pic32prog) in the right places. But that's a
task for another day. ;-)

*Brian

**Pull request merged**
