### PR TITLE
Update Board_Defs.h

### PR DESCRIPTION
**Pull request by aj-ptw**
To satisfy our board variant, we broke out pins 11 and 12 for serial1! Thanks!

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by JacobChrist** [comment]
The changes look sound, I don't know why this fails, but I did notice that the comments did not update with the pins.

Do the comments need to be updated too?

Jacob

**Comment by aj-ptw** [comment]
@JacobChrist good call! Updated it!

**Comment by adamwolf** [comment]
The failure was unrelated.

**Comment by JacobChrist** [comment]
The changes look sound, I don't know why this fails, but I did notice that the comments did not update with the pins.

Do the comments need to be updated too?

Jacob

**Comment by aj-ptw** [comment]
@adamwolf @JacobChrist can we merge this?

**Comment by adamwolf** [comment]
I have no objection on behalf of chipkitbot, but I don't really authorize
merges either :)

**Comment by JacobChrist** [comment]
I have no objection on behalf of myself, but I don't really authorize
merges either :)

If you have tested it and its for your board, I don't see any reason not to merge.

**Comment by EmbeddedMan** [comment]
Agreed - no reason not to merge this. So sorry for it getting lost and sitting around for so long. Not how we try to run things around here. :-)

**Pull request merged**
