### PR TITLE
Fix warnings, added FATFS

### PR DESCRIPTION
**Pull request by KeithV**
Fixed warnings, added FATFS, DSDVOL, RAMVOL, deWebIOServer example.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
ok to test

**Comment by adamwolf** [comment]
ok to test

**Comment by adamwolf** [comment]
Brian, I think it listened to you!!!!

**Comment by EmbeddedMan** [comment]
Wow, there's a first for everything Adam. :-)

**Pull request merged**
